# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CashCow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CashCow
	# add the Firebase pod for Google Analytics
	pod 'Firebase/Core'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'

	# Animations
	# pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
	# pod 'Hero'

  # Auth
  pod 'GoogleSignIn'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'

  # UI
  pod 'EasySocialButton'
  pod 'FontAwesome.swift'
	pod 'SSBouncyButton'
	pod 'Toast-Swift'
end
